title:              PvPqnda
email:              pvpqnda@gmail.com
description:        Map Maker
baseurl:            ""
url:                ""
author:             "PvPqnda"
form_id:            "407887f9-2e9e-4d6f-b246-f39d579a4a5d"

# Social Profiles
twitter_username:   PvPqnda

# Build settings
markdown:           kramdown
paginate:           9
paginate_path:      "/maps/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
