title:              PvPqnda
email:              pvpqnda@gmail.com
description:        Professional Minecraft Map Maker
baseurl:            ""
url:                ""
author:             "PvPqnda"
form_id:            "9a41d72b-a782-4dc4-8148-1a996e1727b8"

# Social Profiles
twitter_username:   PvPqnda
discord_group:      xS57622

# Build settings
markdown:           kramdown
paginate:           9
paginate_path:      "/maps/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
