title:              PvPqnda
email:              pvpqnda@gmail.com
description:        Minecraft Content Creator
baseurl:            ""
url:                ""
author:             "PvPqnda"
form_id:            "9a41d72b-a782-4dc4-8148-1a996e1727b8"
google_analytics:   "UA-164850315-1"

# Social Profiles
twitter_username:   PvPqnda
discord_group:      xS57622
patreon_url:      https://www.patreon.com/pvpqnda

# Build settings
markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
